/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Dashboard } from "./Dashboard";
import { DashboardCountArgs } from "./DashboardCountArgs";
import { DashboardFindManyArgs } from "./DashboardFindManyArgs";
import { DashboardFindUniqueArgs } from "./DashboardFindUniqueArgs";
import { CreateDashboardArgs } from "./CreateDashboardArgs";
import { UpdateDashboardArgs } from "./UpdateDashboardArgs";
import { DeleteDashboardArgs } from "./DeleteDashboardArgs";
import { User } from "../../user/base/User";
import { DashboardService } from "../dashboard.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Dashboard)
export class DashboardResolverBase {
  constructor(
    protected readonly service: DashboardService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "read",
    possession: "any",
  })
  async _dashboardsMeta(
    @graphql.Args() args: DashboardCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Dashboard])
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "read",
    possession: "any",
  })
  async dashboards(
    @graphql.Args() args: DashboardFindManyArgs
  ): Promise<Dashboard[]> {
    return this.service.dashboards(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Dashboard, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "read",
    possession: "own",
  })
  async dashboard(
    @graphql.Args() args: DashboardFindUniqueArgs
  ): Promise<Dashboard | null> {
    const result = await this.service.dashboard(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Dashboard)
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "create",
    possession: "any",
  })
  async createDashboard(
    @graphql.Args() args: CreateDashboardArgs
  ): Promise<Dashboard> {
    return await this.service.createDashboard({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Dashboard)
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "update",
    possession: "any",
  })
  async updateDashboard(
    @graphql.Args() args: UpdateDashboardArgs
  ): Promise<Dashboard | null> {
    try {
      return await this.service.updateDashboard({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Dashboard)
  @nestAccessControl.UseRoles({
    resource: "Dashboard",
    action: "delete",
    possession: "any",
  })
  async deleteDashboard(
    @graphql.Args() args: DeleteDashboardArgs
  ): Promise<Dashboard | null> {
    try {
      return await this.service.deleteDashboard(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: Dashboard): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
